import type {
  KategoriDesaCantik,
  TahunDesaCantik,
} from '@/types/desa-cantik';

export interface KolomKesehatan {
  key: string;
  label: string;
  grup: string;
}

export interface BarisKesehatan {
  label: string;
  nilai: Record<string, number>;
}

export type KelompokTabelKesehatan =
  | 'Kependudukan dan Identitas'
  | 'Kesehatan Ibu dan Keluarga Berencana'
  | 'Disabilitas dan Penyakit'
  | 'Golongan Darah dan Vaksinasi';

export interface TabelKesehatan {
  id: string;
  nomor: string;
  judul: string;
  kelompok: KelompokTabelKesehatan;
  labelBaris: string;
  kolom: KolomKesehatan[];
  baris: BarisKesehatan[];
  jumlah: Record<string, number>;
  catatan?: string;
}

export const SUMBER_DATA_KESEHATAN_2026 =
  'Pendataan Penyusunan Direktori Data Desa Keji Tahun 2026';

export const SUMBER_DATA_KESEHATAN_2025 =
  'Pendataan Penyusunan Direktori Data Desa Keji Tahun 2025';

export const DATA_KESEHATAN_2026: TabelKesehatan[] = [
  {
    id: 'status-perkawinan',
    nomor: 'Tabel 3.1',
    judul:
      'Jumlah Penduduk Menurut Status Perkawinan, Kelompok Umur, dan Jenis Kelamin',
    kelompok: 'Kependudukan dan Identitas',
    labelBaris: 'Status Perkawinan',
    kolom: [
      {
        key: 'u19LakiLaki',
        label: 'Laki-laki',
        grup: '< 19 Tahun',
      },
      {
        key: 'u19Perempuan',
        label: 'Perempuan',
        grup: '< 19 Tahun',
      },
      { key: 'u19Jumlah', label: 'Jumlah', grup: '< 19 Tahun' },
      {
        key: 'u19Sampai24LakiLaki',
        label: 'Laki-laki',
        grup: '19–24 Tahun',
      },
      {
        key: 'u19Sampai24Perempuan',
        label: 'Perempuan',
        grup: '19–24 Tahun',
      },
      {
        key: 'u19Sampai24Jumlah',
        label: 'Jumlah',
        grup: '19–24 Tahun',
      },
      {
        key: 'u25Sampai30LakiLaki',
        label: 'Laki-laki',
        grup: '25–30 Tahun',
      },
      {
        key: 'u25Sampai30Perempuan',
        label: 'Perempuan',
        grup: '25–30 Tahun',
      },
      {
        key: 'u25Sampai30Jumlah',
        label: 'Jumlah',
        grup: '25–30 Tahun',
      },
      {
        key: 'lebih30LakiLaki',
        label: 'Laki-laki',
        grup: '> 30 Tahun',
      },
      {
        key: 'lebih30Perempuan',
        label: 'Perempuan',
        grup: '> 30 Tahun',
      },
      {
        key: 'lebih30Jumlah',
        label: 'Jumlah',
        grup: '> 30 Tahun',
      },
    ],
    baris: [
      {
        label: 'Belum Kawin',
        nilai: {
          u19LakiLaki: 431,
          u19Perempuan: 400,
          u19Jumlah: 831,
          u19Sampai24LakiLaki: 109,
          u19Sampai24Perempuan: 103,
          u19Sampai24Jumlah: 212,
          u25Sampai30LakiLaki: 53,
          u25Sampai30Perempuan: 35,
          u25Sampai30Jumlah: 88,
          lebih30LakiLaki: 58,
          lebih30Perempuan: 22,
          lebih30Jumlah: 80,
        },
      },
      {
        label: 'Cerai Hidup',
        nilai: {
          u19LakiLaki: 0,
          u19Perempuan: 0,
          u19Jumlah: 0,
          u19Sampai24LakiLaki: 0,
          u19Sampai24Perempuan: 3,
          u19Sampai24Jumlah: 3,
          u25Sampai30LakiLaki: 5,
          u25Sampai30Perempuan: 2,
          u25Sampai30Jumlah: 7,
          lebih30LakiLaki: 30,
          lebih30Perempuan: 46,
          lebih30Jumlah: 76,
        },
      },
      {
        label: 'Cerai Mati',
        nilai: {
          u19LakiLaki: 0,
          u19Perempuan: 0,
          u19Jumlah: 0,
          u19Sampai24LakiLaki: 0,
          u19Sampai24Perempuan: 0,
          u19Sampai24Jumlah: 0,
          u25Sampai30LakiLaki: 1,
          u25Sampai30Perempuan: 0,
          u25Sampai30Jumlah: 1,
          lebih30LakiLaki: 47,
          lebih30Perempuan: 115,
          lebih30Jumlah: 162,
        },
      },
      {
        label: 'Kawin/Nikah',
        nilai: {
          u19LakiLaki: 0,
          u19Perempuan: 0,
          u19Jumlah: 0,
          u19Sampai24LakiLaki: 13,
          u19Sampai24Perempuan: 18,
          u19Sampai24Jumlah: 31,
          u25Sampai30LakiLaki: 81,
          u25Sampai30Perempuan: 116,
          u25Sampai30Jumlah: 197,
          lebih30LakiLaki: 711,
          lebih30Perempuan: 662,
          lebih30Jumlah: 1373,
        },
      },
    ],
    jumlah: {
      u19LakiLaki: 431,
      u19Perempuan: 400,
      u19Jumlah: 831,
      u19Sampai24LakiLaki: 122,
      u19Sampai24Perempuan: 124,
      u19Sampai24Jumlah: 246,
      u25Sampai30LakiLaki: 140,
      u25Sampai30Perempuan: 153,
      u25Sampai30Jumlah: 293,
      lebih30LakiLaki: 846,
      lebih30Perempuan: 845,
      lebih30Jumlah: 1691,
    },
  },
  {
    id: 'kartu-identitas',
    nomor: 'Tabel 3.2',
    judul: 'Jumlah Penduduk Menurut Kepemilikan Kartu Identitas',
    kelompok: 'Kependudukan dan Identitas',
    labelBaris: 'RW',
    kolom: [
      {
        key: 'tidakMemiliki',
        label: 'Tidak Memiliki',
        grup: 'Kepemilikan Kartu Identitas',
      },
      {
        key: 'aktaKelahiran',
        label: 'Akta Kelahiran',
        grup: 'Kepemilikan Kartu Identitas',
      },
      {
        key: 'kartuPelajar',
        label: 'Kartu Pelajar',
        grup: 'Kepemilikan Kartu Identitas',
      },
      {
        key: 'ktp',
        label: 'KTP',
        grup: 'Kepemilikan Kartu Identitas',
      },
      {
        key: 'sim',
        label: 'SIM',
        grup: 'Kepemilikan Kartu Identitas',
      },
    ],
    baris: [
      {
        label: 'RW 01',
        nilai: {
          tidakMemiliki: 0,
          aktaKelahiran: 203,
          kartuPelajar: 6,
          ktp: 334,
          sim: 43,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          tidakMemiliki: 0,
          aktaKelahiran: 95,
          kartuPelajar: 7,
          ktp: 209,
          sim: 31,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          tidakMemiliki: 0,
          aktaKelahiran: 124,
          kartuPelajar: 5,
          ktp: 185,
          sim: 15,
        },
      },
    ],
    jumlah: {
      tidakMemiliki: 0,
      aktaKelahiran: 422,
      kartuPelajar: 18,
      ktp: 728,
      sim: 89,
    },
  },
  {
    id: 'status-kehamilan',
    nomor: 'Tabel 3.3',
    judul:
      'Jumlah Penduduk Wanita Umur 10–49 Tahun yang Berstatus Kawin Menurut Status Kehamilan',
    kelompok: 'Kesehatan Ibu dan Keluarga Berencana',
    labelBaris: 'RW',
    kolom: [
      { key: 'ya', label: 'Ya', grup: 'Status Kehamilan' },
      { key: 'tidak', label: 'Tidak', grup: 'Status Kehamilan' },
    ],
    baris: [
      { label: 'RW 01', nilai: { ya: 8, tidak: 222 } },
      { label: 'RW 02', nilai: { ya: 5, tidak: 215 } },
      { label: 'RW 03', nilai: { ya: 1, tidak: 87 } },
    ],
    jumlah: { ya: 14, tidak: 524 },
  },
  {
    id: 'penggunaan-alat-kb',
    nomor: 'Tabel 3.4',
    judul:
      'Jumlah Penduduk Wanita Umur 10–49 Tahun yang Berstatus Kawin Menurut Penggunaan Alat KB',
    kelompok: 'Kesehatan Ibu dan Keluarga Berencana',
    labelBaris: 'RW',
    kolom: [
      {
        key: 'mowTubektomi',
        label: 'MOW/Tubektomi',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'mopVasektomi',
        label: 'MOP/Vasektomi',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'akdrIudSpiral',
        label: 'AKDR/IUD/Spiral',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'suntikanKb',
        label: 'Suntikan KB',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'susukKb',
        label: 'Susuk KB/Norplan/Implanon/Alwalit',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'pilKb',
        label: 'Pil KB',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'kondom',
        label: 'Kondom/Karet KB',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'intraveg',
        label: 'Intraveg/Tisue/Kondom Wanita',
        grup: 'Penggunaan Alat KB',
      },
      {
        key: 'caraTradisional',
        label: 'Cara Tradisional',
        grup: 'Penggunaan Alat KB',
      },
    ],
    baris: [
      {
        label: 'RW 01',
        nilai: {
          mowTubektomi: 8,
          mopVasektomi: 1,
          akdrIudSpiral: 15,
          suntikanKb: 41,
          susukKb: 19,
          pilKb: 9,
          kondom: 20,
          intraveg: 0,
          caraTradisional: 71,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          mowTubektomi: 6,
          mopVasektomi: 0,
          akdrIudSpiral: 26,
          suntikanKb: 39,
          susukKb: 8,
          pilKb: 17,
          kondom: 26,
          intraveg: 0,
          caraTradisional: 29,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          mowTubektomi: 3,
          mopVasektomi: 0,
          akdrIudSpiral: 6,
          suntikanKb: 29,
          susukKb: 8,
          pilKb: 2,
          kondom: 1,
          intraveg: 0,
          caraTradisional: 4,
        },
      },
    ],
    jumlah: {
      mowTubektomi: 17,
      mopVasektomi: 1,
      akdrIudSpiral: 47,
      suntikanKb: 109,
      susukKb: 35,
      pilKb: 28,
      kondom: 47,
      intraveg: 0,
      caraTradisional: 104,
    },
  },
  {
    id: 'jenis-disabilitas',
    nomor: 'Tabel 3.5',
    judul: 'Jumlah Penduduk Menurut Jenis Cacat',
    kelompok: 'Disabilitas dan Penyakit',
    labelBaris: 'RW',
    kolom: [
      {
        key: 'tidakCacat',
        label: 'Tidak cacat',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaDaksa',
        label: 'Tuna daksa/cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaNetra',
        label: 'Tuna netra/buta',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRungu',
        label: 'Tuna rungu',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaWicara',
        label: 'Tuna wicara',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRunguWicara',
        label: 'Tuna rungu & wicara',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaNetraDaksa',
        label: 'Tuna netra & cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaNetraRunguWicara',
        label: 'Tuna netra, rungu, & wicara',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRunguWicaraDaksa',
        label: 'Tuna rungu, wicara, & cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRunguWicaraNetraDaksa',
        label: 'Tuna rungu, wicara, netra, & cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'cacatMentalRetardasi',
        label: 'Cacat mental retardasi',
        grup: 'Jenis Cacat',
      },
      {
        key: 'mantanGangguanJiwa',
        label: 'Mantan penderita gangguan jiwa',
        grup: 'Jenis Cacat',
      },
      {
        key: 'cacatFisikMental',
        label: 'Cacat fisik & mental',
        grup: 'Jenis Cacat',
      },
    ],
    baris: [
      {
        label: 'RW 01',
        nilai: {
          tidakCacat: 1435,
          tunaDaksa: 6,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 2,
          cacatFisikMental: 0,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          tidakCacat: 1060,
          tunaDaksa: 6,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 3,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          tidakCacat: 556,
          tunaDaksa: 2,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 2,
          tunaRunguWicara: 1,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 2,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
    ],
    jumlah: {
      tidakCacat: 3051,
      tunaDaksa: 14,
      tunaNetra: 0,
      tunaRungu: 2,
      tunaWicara: 4,
      tunaRunguWicara: 1,
      tunaNetraDaksa: 0,
      tunaNetraRunguWicara: 0,
      tunaRunguWicaraDaksa: 0,
      tunaRunguWicaraNetraDaksa: 0,
      cacatMentalRetardasi: 6,
      mantanGangguanJiwa: 2,
      cacatFisikMental: 0,
    },
  },
  {
    id: 'penyakit-kronis',
    nomor: 'Tabel 3.6',
    judul: 'Jumlah Penduduk Menurut Penyakit Kronis/Menahun',
    kelompok: 'Disabilitas dan Penyakit',
    labelBaris: 'RW',
    kolom: [
      {
        key: 'tidakAda',
        label: 'Tidak ada',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'hipertensi',
        label: 'Hipertensi (tekanan darah tinggi)',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'rematik',
        label: 'Rematik',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'asma',
        label: 'Asma',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'masalahJantung',
        label: 'Masalah jantung',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'diabetes',
        label: 'Diabetes (kencing manis)',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'tuberculosis',
        label: 'Tuberculosis (TBC)',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'stroke',
        label: 'Stroke',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'kanker',
        label: 'Kanker atau tumor ganas',
        grup: 'Penyakit Kronis/Menahun',
      },
      {
        key: 'lainnya',
        label: 'Lainnya (gagal ginjal, paru-paru flek, dan sejenisnya)',
        grup: 'Penyakit Kronis/Menahun',
      },
    ],
    baris: [
      {
        label: 'RW 01',
        nilai: {
          tidakAda: 0,
          hipertensi: 4,
          rematik: 1,
          asma: 0,
          masalahJantung: 4,
          diabetes: 3,
          tuberculosis: 0,
          stroke: 11,
          kanker: 0,
          lainnya: 1,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          tidakAda: 0,
          hipertensi: 27,
          rematik: 2,
          asma: 2,
          masalahJantung: 3,
          diabetes: 9,
          tuberculosis: 1,
          stroke: 4,
          kanker: 3,
          lainnya: 6,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          tidakAda: 0,
          hipertensi: 10,
          rematik: 1,
          asma: 0,
          masalahJantung: 1,
          diabetes: 7,
          tuberculosis: 0,
          stroke: 2,
          kanker: 0,
          lainnya: 5,
        },
      },
    ],
    jumlah: {
      tidakAda: 0,
      hipertensi: 41,
      rematik: 4,
      asma: 2,
      masalahJantung: 8,
      diabetes: 19,
      tuberculosis: 1,
      stroke: 17,
      kanker: 3,
      lainnya: 12,
    },
  },
  {
    id: 'golongan-darah',
    nomor: 'Tabel 3.7',
    judul: 'Jumlah Penduduk Menurut Golongan Darah',
    kelompok: 'Golongan Darah dan Vaksinasi',
    labelBaris: 'RW',
    kolom: [
      { key: 'a', label: 'A', grup: 'Golongan Darah' },
      { key: 'b', label: 'B', grup: 'Golongan Darah' },
      { key: 'ab', label: 'AB', grup: 'Golongan Darah' },
      { key: 'o', label: 'O', grup: 'Golongan Darah' },
      {
        key: 'tidakTahu',
        label: 'Tidak Tahu',
        grup: 'Golongan Darah',
      },
    ],
    baris: [
      {
        label: 'RW 01',
        nilai: { a: 63, b: 80, ab: 37, o: 146, tidakTahu: 1119 },
      },
      {
        label: 'RW 02',
        nilai: { a: 78, b: 119, ab: 35, o: 137, tidakTahu: 700 },
      },
      {
        label: 'RW 03',
        nilai: { a: 13, b: 22, ab: 9, o: 66, tidakTahu: 454 },
      },
    ],
    jumlah: { a: 154, b: 221, ab: 81, o: 349, tidakTahu: 2273 },
  },
  {
    id: 'disabilitas-menurut-umur',
    nomor: 'Tabel 3.8',
    judul: 'Jumlah Penduduk Disabilitas Menurut Umur',
    kelompok: 'Disabilitas dan Penyakit',
    labelBaris: 'Umur (Tahun)',
    kolom: [
      {
        key: 'tidakCacat',
        label: 'Tidak cacat',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaDaksa',
        label: 'Tuna daksa/cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaNetra',
        label: 'Tuna netra/buta',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRungu',
        label: 'Tuna rungu',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaWicara',
        label: 'Tuna wicara',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRunguWicara',
        label: 'Tuna rungu & wicara',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaNetraDaksa',
        label: 'Tuna netra & cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaNetraRunguWicara',
        label: 'Tuna netra, rungu, & wicara',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRunguWicaraDaksa',
        label: 'Tuna rungu, wicara, & cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'tunaRunguWicaraNetraDaksa',
        label: 'Tuna rungu, wicara, netra, & cacat tubuh',
        grup: 'Jenis Cacat',
      },
      {
        key: 'cacatMentalRetardasi',
        label: 'Cacat mental retardasi',
        grup: 'Jenis Cacat',
      },
      {
        key: 'mantanGangguanJiwa',
        label: 'Mantan penderita gangguan jiwa',
        grup: 'Jenis Cacat',
      },
      {
        key: 'cacatFisikMental',
        label: 'Cacat fisik & mental',
        grup: 'Jenis Cacat',
      },
    ],
    baris: [
      {
        label: '00–04',
        nilai: {
          tidakCacat: 194,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '05–09',
        nilai: {
          tidakCacat: 233,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '10–14',
        nilai: {
          tidakCacat: 239,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '15–19',
        nilai: {
          tidakCacat: 198,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '20–24',
        nilai: {
          tidakCacat: 206,
          tunaDaksa: 2,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '25–29',
        nilai: {
          tidakCacat: 238,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '30–34',
        nilai: {
          tidakCacat: 288,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '35–39',
        nilai: {
          tidakCacat: 262,
          tunaDaksa: 2,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '40–44',
        nilai: {
          tidakCacat: 226,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 2,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '45–49',
        nilai: {
          tidakCacat: 213,
          tunaDaksa: 3,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 1,
          cacatFisikMental: 0,
        },
      },
      {
        label: '50–54',
        nilai: {
          tidakCacat: 179,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '55–59',
        nilai: {
          tidakCacat: 174,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 1,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '60–64',
        nilai: {
          tidakCacat: 158,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '65–69',
        nilai: {
          tidakCacat: 112,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 1,
          cacatFisikMental: 0,
        },
      },
      {
        label: '70–74',
        nilai: {
          tidakCacat: 52,
          tunaDaksa: 2,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '75+',
        nilai: {
          tidakCacat: 60,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
    ],
    jumlah: {
      tidakCacat: 3078,
      tunaDaksa: 14,
      tunaNetra: 0,
      tunaRungu: 2,
      tunaWicara: 4,
      tunaRunguWicara: 1,
      tunaNetraDaksa: 0,
      tunaNetraRunguWicara: 0,
      tunaRunguWicaraDaksa: 0,
      tunaRunguWicaraNetraDaksa: 0,
      cacatMentalRetardasi: 6,
      mantanGangguanJiwa: 2,
      cacatFisikMental: 0,
    },
    catatan:
      'Baris Jumlah pada kolom Tidak cacat tertulis 3.078 di dokumen sumber, sedangkan penjumlahan kelompok umur menghasilkan 3.032. Nilai 3.078 dipertahankan agar sama dengan sumber.',
  },
  {
    id: 'vaksinasi',
    nomor: 'Tabel 3.9',
    judul: 'Vaksin di Desa Keji',
    kelompok: 'Golongan Darah dan Vaksinasi',
    labelBaris: 'RW',
    kolom: [
      { key: 'belumVaksin', label: 'Belum Vaksin', grup: 'Vaksin' },
      { key: 'dosis1', label: 'Dosis 1', grup: 'Vaksin' },
      { key: 'dosis2', label: 'Dosis 2', grup: 'Vaksin' },
      { key: 'booster', label: 'Booster', grup: 'Vaksin' },
    ],
    baris: [
      {
        label: 'RW 01',
        nilai: { belumVaksin: 221, dosis1: 136, dosis2: 644, booster: 320 },
      },
      {
        label: 'RW 02',
        nilai: { belumVaksin: 151, dosis1: 72, dosis2: 435, booster: 268 },
      },
      {
        label: 'RW 03',
        nilai: { belumVaksin: 54, dosis1: 55, dosis2: 234, booster: 179 },
      },
    ],
    jumlah: {
      belumVaksin: 426,
      dosis1: 263,
      dosis2: 1313,
      booster: 767,
    },
  },
];

const NILAI_KESEHATAN_2025: Record<
  string,
  Pick<TabelKesehatan, 'baris' | 'jumlah' | 'catatan'>
> = {
  'status-perkawinan': {
    baris: [
      {
        label: 'Belum Kawin',
        nilai: {
          u19LakiLaki: 426,
          u19Perempuan: 399,
          u19Jumlah: 825,
          u19Sampai24LakiLaki: 106,
          u19Sampai24Perempuan: 91,
          u19Sampai24Jumlah: 197,
          u25Sampai30LakiLaki: 54,
          u25Sampai30Perempuan: 38,
          u25Sampai30Jumlah: 92,
          lebih30LakiLaki: 54,
          lebih30Perempuan: 18,
          lebih30Jumlah: 72,
        },
      },
      {
        label: 'Cerai Hidup',
        nilai: {
          u19LakiLaki: 0,
          u19Perempuan: 0,
          u19Jumlah: 0,
          u19Sampai24LakiLaki: 1,
          u19Sampai24Perempuan: 3,
          u19Sampai24Jumlah: 4,
          u25Sampai30LakiLaki: 4,
          u25Sampai30Perempuan: 3,
          u25Sampai30Jumlah: 7,
          lebih30LakiLaki: 31,
          lebih30Perempuan: 45,
          lebih30Jumlah: 76,
        },
      },
      {
        label: 'Cerai Mati',
        nilai: {
          u19LakiLaki: 0,
          u19Perempuan: 0,
          u19Jumlah: 0,
          u19Sampai24LakiLaki: 0,
          u19Sampai24Perempuan: 0,
          u19Sampai24Jumlah: 0,
          u25Sampai30LakiLaki: 1,
          u25Sampai30Perempuan: 0,
          u25Sampai30Jumlah: 1,
          lebih30LakiLaki: 48,
          lebih30Perempuan: 113,
          lebih30Jumlah: 161,
        },
      },
      {
        label: 'Kawin/Nikah',
        nilai: {
          u19LakiLaki: 0,
          u19Perempuan: 0,
          u19Jumlah: 0,
          u19Sampai24LakiLaki: 17,
          u19Sampai24Perempuan: 24,
          u19Sampai24Jumlah: 41,
          u25Sampai30LakiLaki: 86,
          u25Sampai30Perempuan: 125,
          u25Sampai30Jumlah: 211,
          lebih30LakiLaki: 703,
          lebih30Perempuan: 646,
          lebih30Jumlah: 1349,
        },
      },
    ],
    jumlah: {
      u19LakiLaki: 426,
      u19Perempuan: 399,
      u19Jumlah: 825,
      u19Sampai24LakiLaki: 124,
      u19Sampai24Perempuan: 118,
      u19Sampai24Jumlah: 242,
      u25Sampai30LakiLaki: 145,
      u25Sampai30Perempuan: 166,
      u25Sampai30Jumlah: 311,
      lebih30LakiLaki: 836,
      lebih30Perempuan: 822,
      lebih30Jumlah: 1658,
    },
  },
  'kartu-identitas': {
    baris: [
      {
        label: 'RW 01',
        nilai: {
          tidakMemiliki: 0,
          aktaKelahiran: 202,
          kartuPelajar: 6,
          ktp: 334,
          sim: 43,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          tidakMemiliki: 0,
          aktaKelahiran: 99,
          kartuPelajar: 8,
          ktp: 215,
          sim: 31,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          tidakMemiliki: 0,
          aktaKelahiran: 124,
          kartuPelajar: 5,
          ktp: 185,
          sim: 15,
        },
      },
    ],
    jumlah: {
      tidakMemiliki: 0,
      aktaKelahiran: 425,
      kartuPelajar: 19,
      ktp: 734,
      sim: 89,
    },
  },
  'status-kehamilan': {
    baris: [
      { label: 'RW 01', nilai: { ya: 7, tidak: 225 } },
      { label: 'RW 02', nilai: { ya: 6, tidak: 219 } },
      { label: 'RW 03', nilai: { ya: 2, tidak: 89 } },
    ],
    jumlah: { ya: 15, tidak: 533 },
  },
  'penggunaan-alat-kb': {
    baris: [
      {
        label: 'RW 01',
        nilai: {
          mowTubektomi: 8,
          mopVasektomi: 1,
          akdrIudSpiral: 15,
          suntikanKb: 42,
          susukKb: 19,
          pilKb: 10,
          kondom: 18,
          intraveg: 0,
          caraTradisional: 72,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          mowTubektomi: 7,
          mopVasektomi: 0,
          akdrIudSpiral: 26,
          suntikanKb: 41,
          susukKb: 7,
          pilKb: 18,
          kondom: 24,
          intraveg: 0,
          caraTradisional: 28,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          mowTubektomi: 3,
          mopVasektomi: 0,
          akdrIudSpiral: 6,
          suntikanKb: 31,
          susukKb: 8,
          pilKb: 2,
          kondom: 1,
          intraveg: 0,
          caraTradisional: 4,
        },
      },
    ],
    jumlah: {
      mowTubektomi: 18,
      mopVasektomi: 1,
      akdrIudSpiral: 47,
      suntikanKb: 114,
      susukKb: 34,
      pilKb: 30,
      kondom: 43,
      intraveg: 0,
      caraTradisional: 104,
    },
    catatan:
      'Urutan label Pil KB, Kondom/Karet KB, dan Intraveg/Tisue/Kondom Wanita pada lanjutan Tabel 3.4 tampak bergeser. Nilai 30, 43, dan 0 mengikuti grafik ringkasan Kesehatan 2025 pada dokumen sumber.',
  },
  'jenis-disabilitas': {
    baris: [
      {
        label: 'RW 01',
        nilai: {
          tidakCacat: 1435,
          tunaDaksa: 6,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 2,
          cacatFisikMental: 0,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          tidakCacat: 1054,
          tunaDaksa: 6,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 3,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          tidakCacat: 556,
          tunaDaksa: 2,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 2,
          tunaRunguWicara: 1,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 2,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
    ],
    jumlah: {
      tidakCacat: 3045,
      tunaDaksa: 14,
      tunaNetra: 0,
      tunaRungu: 2,
      tunaWicara: 4,
      tunaRunguWicara: 1,
      tunaNetraDaksa: 0,
      tunaNetraRunguWicara: 0,
      tunaRunguWicaraDaksa: 0,
      tunaRunguWicaraNetraDaksa: 0,
      cacatMentalRetardasi: 6,
      mantanGangguanJiwa: 2,
      cacatFisikMental: 0,
    },
  },
  'penyakit-kronis': {
    baris: [
      {
        label: 'RW 01',
        nilai: {
          tidakAda: 0,
          hipertensi: 4,
          rematik: 1,
          asma: 0,
          masalahJantung: 4,
          diabetes: 5,
          tuberculosis: 0,
          stroke: 13,
          kanker: 0,
          lainnya: 1,
        },
      },
      {
        label: 'RW 02',
        nilai: {
          tidakAda: 0,
          hipertensi: 27,
          rematik: 2,
          asma: 2,
          masalahJantung: 3,
          diabetes: 9,
          tuberculosis: 1,
          stroke: 4,
          kanker: 3,
          lainnya: 7,
        },
      },
      {
        label: 'RW 03',
        nilai: {
          tidakAda: 0,
          hipertensi: 10,
          rematik: 1,
          asma: 0,
          masalahJantung: 1,
          diabetes: 7,
          tuberculosis: 0,
          stroke: 2,
          kanker: 0,
          lainnya: 5,
        },
      },
    ],
    jumlah: {
      tidakAda: 0,
      hipertensi: 41,
      rematik: 4,
      asma: 2,
      masalahJantung: 8,
      diabetes: 21,
      tuberculosis: 1,
      stroke: 19,
      kanker: 3,
      lainnya: 13,
    },
  },
  'golongan-darah': {
    baris: [
      {
        label: 'RW 01',
        nilai: { a: 61, b: 81, ab: 37, o: 145, tidakTahu: 1121 },
      },
      {
        label: 'RW 02',
        nilai: { a: 78, b: 119, ab: 35, o: 137, tidakTahu: 694 },
      },
      {
        label: 'RW 03',
        nilai: { a: 13, b: 22, ab: 9, o: 66, tidakTahu: 454 },
      },
    ],
    jumlah: { a: 152, b: 222, ab: 81, o: 348, tidakTahu: 2269 },
  },
  'disabilitas-menurut-umur': {
    baris: [
      {
        label: '00–04',
        nilai: {
          tidakCacat: 194,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '05–09',
        nilai: {
          tidakCacat: 233,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '10–14',
        nilai: {
          tidakCacat: 227,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '15–19',
        nilai: {
          tidakCacat: 200,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '20–24',
        nilai: {
          tidakCacat: 206,
          tunaDaksa: 2,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '25–29',
        nilai: {
          tidakCacat: 252,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '30–34',
        nilai: {
          tidakCacat: 286,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '35–39',
        nilai: {
          tidakCacat: 252,
          tunaDaksa: 2,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '40–44',
        nilai: {
          tidakCacat: 230,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '45–49',
        nilai: {
          tidakCacat: 211,
          tunaDaksa: 3,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 1,
          cacatFisikMental: 0,
        },
      },
      {
        label: '50–54',
        nilai: {
          tidakCacat: 173,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '55–59',
        nilai: {
          tidakCacat: 176,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 1,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 1,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '60–64',
        nilai: {
          tidakCacat: 156,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '65–69',
        nilai: {
          tidakCacat: 101,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 1,
          tunaWicara: 1,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 1,
          cacatFisikMental: 0,
        },
      },
      {
        label: '70–74',
        nilai: {
          tidakCacat: 54,
          tunaDaksa: 1,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
      {
        label: '75+',
        nilai: {
          tidakCacat: 56,
          tunaDaksa: 0,
          tunaNetra: 0,
          tunaRungu: 0,
          tunaWicara: 0,
          tunaRunguWicara: 0,
          tunaNetraDaksa: 0,
          tunaNetraRunguWicara: 0,
          tunaRunguWicaraDaksa: 0,
          tunaRunguWicaraNetraDaksa: 0,
          cacatMentalRetardasi: 0,
          mantanGangguanJiwa: 0,
          cacatFisikMental: 0,
        },
      },
    ],
    jumlah: {
      tidakCacat: 3052,
      tunaDaksa: 14,
      tunaNetra: 0,
      tunaRungu: 2,
      tunaWicara: 4,
      tunaRunguWicara: 1,
      tunaNetraDaksa: 0,
      tunaNetraRunguWicara: 0,
      tunaRunguWicaraDaksa: 0,
      tunaRunguWicaraNetraDaksa: 0,
      cacatMentalRetardasi: 6,
      mantanGangguanJiwa: 2,
      cacatFisikMental: 0,
    },
    catatan:
      'Baris Jumlah pada kolom Tidak cacat tertulis 3.052 di dokumen sumber, sedangkan penjumlahan kelompok umur menghasilkan 3.007. Nilai 3.052 dipertahankan agar sama dengan sumber.',
  },
  vaksinasi: {
    baris: [
      {
        label: 'RW 01',
        nilai: { belumVaksin: 224, dosis1: 138, dosis2: 647, booster: 321 },
      },
      {
        label: 'RW 02',
        nilai: { belumVaksin: 76, dosis1: 45, dosis2: 343, booster: 229 },
      },
      {
        label: 'RW 03',
        nilai: { belumVaksin: 54, dosis1: 55, dosis2: 234, booster: 179 },
      },
    ],
    jumlah: {
      belumVaksin: 354,
      dosis1: 238,
      dosis2: 1224,
      booster: 729,
    },
  },
};

export const DATA_KESEHATAN_2025: TabelKesehatan[] =
  DATA_KESEHATAN_2026.map((tabel) => {
    const nilaiTahun = NILAI_KESEHATAN_2025[tabel.id];

    if (!nilaiTahun) {
      throw new Error(
        `Data Kesehatan 2025 untuk ${tabel.id} belum tersedia.`,
      );
    }

    return {
      ...tabel,
      ...nilaiTahun,
    };
  });

export function getDataKesehatan(
  kategori: KategoriDesaCantik,
  tahun: TahunDesaCantik,
) {
  if (kategori !== 'kesehatan') {
    return [];
  }

  if (tahun === 2025) {
    return DATA_KESEHATAN_2025;
  }

  if (tahun === 2026) {
    return DATA_KESEHATAN_2026;
  }

  return [];
}